name 'seedbox'
maintainer 'Chris Down'
maintainer_email 'chris@chrisdown.name'
license 'ISC'
description 'Sets up a seedbox'
long_description 'Sets up a seedbox'
version '1.0.0'
issues_url 'https://github.com/cdown/seedbox-cookbook/issues'
source_url 'https://github.com/cdown/seedbox-cookbook'

depends 'rtorrent'
depends 'openssh'
depends 'ssh_authorized_keys'
depends 'sudo'
depends 'unattended-upgrades'
